//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylphyHorn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylphyHorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provided by Windows.
        /// </summary>
        public static string Common_ProvidedByWinows {
            get {
                return ResourceManager.GetString("Common_ProvidedByWinows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Common_Reference {
            get {
                return ResourceManager.GetString("Common_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Settings_Background {
            get {
                return ResourceManager.GetString("Settings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the background for each desktop.
        /// </summary>
        public static string Settings_Background_ChangeBackground {
            get {
                return ResourceManager.GetString("Settings_Background_ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop background.
        /// </summary>
        public static string Settings_Background_Desktop {
            get {
                return ResourceManager.GetString("Settings_Background_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported image formats: JPEG, PNG, BMP.
        /// </summary>
        public static string Settings_Background_Note1 {
            get {
                return ResourceManager.GetString("Settings_Background_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Please prepare image files with the virtual desktop number as filename (e.g. &quot;1.png&quot;, &quot;2.png&quot;, ...)..
        /// </summary>
        public static string Settings_Background_Note2 {
            get {
                return ResourceManager.GetString("Settings_Background_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background Images Folder.
        /// </summary>
        public static string Settings_Background_SelectionDialog {
            get {
                return ResourceManager.GetString("Settings_Background_SelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source image folder path.
        /// </summary>
        public static string Settings_Background_SourceImageFolder {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close desktop.
        /// </summary>
        public static string Settings_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and switch left:.
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchLeft {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and switch right:.
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchRight {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop switching.
        /// </summary>
        public static string Settings_DesktopSwitching {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop virtual desktops.
        /// </summary>
        public static string Settings_DesktopSwitching_Loop {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override OS default key combination (Ctrl+Win+Left and Right).
        /// </summary>
        public static string Settings_DesktopSwitching_OverrideOS {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_OverrideOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart app in order for the changes to take all effect..
        /// </summary>
        public static string Settings_Language_RequireRestartMessage {
            get {
                return ResourceManager.GetString("Settings_Language_RequireRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to adjacent desktop.
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left (Switch):.
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (Switch):.
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_RightAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_RightAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to created new desktop.
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch only.
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_CreateOnly {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_CreateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move:.
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_Move {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move (Switch):.
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_MoveAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_MoveAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination displays.
        /// </summary>
        public static string Settings_MultipleDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All displays.
        /// </summary>
        public static string Settings_MultipleDisplays_AllDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current display.
        /// </summary>
        public static string Settings_MultipleDisplays_CurrentDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_CurrentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display {0}: {1}.
        /// </summary>
        public static string Settings_MultipleDisplays_EachDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_EachDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a notification when switched virtual desktop.
        /// </summary>
        public static string Settings_Notification_Display {
            get {
                return ResourceManager.GetString("Settings_Notification_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Duration for Notification Messages:.
        /// </summary>
        public static string Settings_Notification_Display_Duration {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Settings_Notification_Display_Duration_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification window placement.
        /// </summary>
        public static string Settings_NotificationWindowPlacement {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom center.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top center.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin window:.
        /// </summary>
        public static string Settings_Pin {
            get {
                return ResourceManager.GetString("Settings_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin/Unpin toggle:.
        /// </summary>
        public static string Settings_PinToggle {
            get {
                return ResourceManager.GetString("Settings_PinToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin window to all desktops.
        /// </summary>
        public static string Settings_PinWindow {
            get {
                return ResourceManager.GetString("Settings_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin window from app to all desktops.
        /// </summary>
        public static string Settings_PinWindowFromApp {
            get {
                return ResourceManager.GetString("Settings_PinWindowFromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement.
        /// </summary>
        public static string Settings_Placement {
            get {
                return ResourceManager.GetString("Settings_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut key.
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaticaly start at logon.
        /// </summary>
        public static string Settings_Startup_Automaticaly {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin window:.
        /// </summary>
        public static string Settings_Unpin {
            get {
                return ResourceManager.GetString("Settings_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is running in the background..
        /// </summary>
        public static string TaskTray_FirstTimeMessage {
            get {
                return ResourceManager.GetString("TaskTray_FirstTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit (X).
        /// </summary>
        public static string TaskTray_Menu_Exit {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings (S).
        /// </summary>
        public static string TaskTray_Menu_Settings {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Settings", resourceCulture);
            }
        }
    }
}
