//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylphyHorn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylphyHorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   provided by Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ProvidedByWinows {
            get {
                return ResourceManager.GetString("Common_ProvidedByWinows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Reference {
            get {
                return ResourceManager.GetString("Common_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background {
            get {
                return ResourceManager.GetString("Settings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the background for each desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_ChangeBackground {
            get {
                return ResourceManager.GetString("Settings_Background_ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Desktop {
            get {
                return ResourceManager.GetString("Settings_Background_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported image formats: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note1 {
            get {
                return ResourceManager.GetString("Settings_Background_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note: Please prepare image files with the virtual desktop number as filename (e.g. &quot;1.png&quot;, &quot;2.png&quot;, ...). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note2 {
            get {
                return ResourceManager.GetString("Settings_Background_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a default position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position {
            get {
                return ResourceManager.GetString("Settings_Background_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Center {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fill {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fit {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Span に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Span {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Stretch {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Tile {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Background Images Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SelectionDialog {
            get {
                return ResourceManager.GetString("Settings_Background_SelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SourceImageFolder {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchLeft {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchRight {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop switching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop virtual desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_Loop {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override OS default key combination (Ctrl+Win+Left and Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_OverrideOS {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_OverrideOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must restart app in order for the changes to take all effect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language_RequireRestartMessage {
            get {
                return ResourceManager.GetString("Settings_Language_RequireRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Log {
            get {
                return ResourceManager.GetString("Settings_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer {
            get {
                return ResourceManager.GetString("Settings_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events that occurred during execution are displayed here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer_Description {
            get {
                return ResourceManager.GetString("Settings_LogViewer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to adjacent desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_RightAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_RightAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to created new desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_CreateOnly {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_CreateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_Move {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_MoveAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_MoveAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_AllDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_CurrentDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_CurrentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_EachDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_EachDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a notification when switched virtual desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display {
            get {
                return ResourceManager.GetString("Settings_Notification_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Duration for Notification Messages: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification window placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Pin {
            get {
                return ResourceManager.GetString("Settings_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin/Unpin toggle: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinToggle {
            get {
                return ResourceManager.GetString("Settings_PinToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindow {
            get {
                return ResourceManager.GetString("Settings_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window from app to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindowFromApp {
            get {
                return ResourceManager.GetString("Settings_PinWindowFromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Placement {
            get {
                return ResourceManager.GetString("Settings_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automaticaly start at logon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup_Automaticaly {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show current desktop info in tray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToggleTrayIconInfo {
            get {
                return ResourceManager.GetString("Settings_ToggleTrayIconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Unpin {
            get {
                return ResourceManager.GetString("Settings_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application is running in the background. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_FirstTimeMessage {
            get {
                return ResourceManager.GetString("TaskTray_FirstTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit (X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Exit {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Settings (S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Settings {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Settings", resourceCulture);
            }
        }
    }
}
