//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylphyHorn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylphyHorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel installation?.
        /// </summary>
        public static string InstallCancellation {
            get {
                return ResourceManager.GetString("InstallCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Completed.
        /// </summary>
        public static string InstallCompleted {
            get {
                return ResourceManager.GetString("InstallCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylphyHorn Engine has been installed on your PC..
        /// </summary>
        public static string InstallCompleted_Message {
            get {
                return ResourceManager.GetString("InstallCompleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インストール失敗.
        /// </summary>
        public static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylphyHorn Engine のインストールに失敗しました。.
        /// </summary>
        public static string InstallFailed_Message {
            get {
                return ResourceManager.GetString("InstallFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SylphyHorn Engine.
        /// </summary>
        public static string InstallMode_Header {
            get {
                return ResourceManager.GetString("InstallMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SylphyHorn Engine to your PC.
        ///Work will be completed soon..
        /// </summary>
        public static string InstallMode_Message {
            get {
                return ResourceManager.GetString("InstallMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect components....
        /// </summary>
        public static string PreparationMode_Message {
            get {
                return ResourceManager.GetString("PreparationMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Progress_Install {
            get {
                return ResourceManager.GetString("Progress_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Progress_Uninstall {
            get {
                return ResourceManager.GetString("Progress_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Completed.
        /// </summary>
        public static string UninstallCompleted {
            get {
                return ResourceManager.GetString("UninstallCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylphyHorn Engine has been uninstalled from your PC..
        /// </summary>
        public static string UninstallCompleted_Message {
            get {
                return ResourceManager.GetString("UninstallCompleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アンインストール失敗.
        /// </summary>
        public static string UninstallFailed {
            get {
                return ResourceManager.GetString("UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylphyHorn Engine のアンインストールに失敗しました。.
        /// </summary>
        public static string UninstallFailed_Message {
            get {
                return ResourceManager.GetString("UninstallFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall SylphyHorn Engine.
        /// </summary>
        public static string UninstallMode_Header {
            get {
                return ResourceManager.GetString("UninstallMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall SylphyHorn Engine from your PC..
        /// </summary>
        public static string UninstallMode_Message {
            get {
                return ResourceManager.GetString("UninstallMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylphyHorn Installer.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
